# Generated by Django 2.2.3 on 2019-07-17 14:45

import blog.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='author',
            field=models.CharField(default='anonymous', max_length=60),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='lnglat',
            field=models.CharField(default='anonym', help_text='경도,위도 포맷으로 입력', max_length=50, validators=[blog.models.lnglat_validator]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='tags',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='post',
            name='content',
            field=models.TextField(verbose_name='내용'),
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(max_length=100, verbose_name='제목'),
        ),
    ]
