# Generated by Django 2.2.3 on 2019-08-02 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_post_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='photo',
            field=models.ImageField(blank=True, upload_to='media2/super/%Y/%m/%d'),
        ),
    ]
